language: ruby
rvm:
  - 2.3.4
script: rake site:generate
deploy:
  provider: pages
  local_dir: _site
  skip_cleanup: true
  github_token: $GITHUB_API_KEY # Set in travis-ci.org dashboard
  on:
    branch: master
