name: Random Presence
description: Of my thoughts & scribblings ...
permalink: /:year/:month/:title/
highlighter: pygments
exclude: ['Gemfile','Gemfile.lock','Rakefile','sass','vendor']
url: http://prasans.info
paginate: 20
paginate_path: "blog/page:num"